INSERT INTO `lcodatabase`.`state` (`state_name`) VALUES ('Gujarat');
INSERT INTO `lcodatabase`.`state` (`state_name`) VALUES ('Karnataka');
INSERT INTO `lcodatabase`.`state` (`state_name`) VALUES ('Maharashtra');
INSERT INTO `lcodatabase`.`state` (`state_name`) VALUES ('Rajasthan');
INSERT INTO `lcodatabase`.`state` (`state_name`) VALUES ('NCR');
INSERT INTO `lcodatabase`.`state` (`state_name`) VALUES ('Bihar');
INSERT INTO `lcodatabase`.`state` (`state_name`) VALUES ('Jharkhand');
INSERT INTO `lcodatabase`.`state` (`state_name`) VALUES ('Haryana');
INSERT INTO `lcodatabase`.`state` (`state_name`) VALUES ('Kerala');
INSERT INTO `lcodatabase`.`state` (`state_name`) VALUES ('Uttrakhand');
INSERT INTO `lcodatabase`.`state` (`state_name`) VALUES ('Uttar Pradesh');
INSERT INTO `lcodatabase`.`state` (`state_name`) VALUES ('West Bengal');


INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('1', 'Vapi Silvassa and surrounding areas');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('1', 'Surat Dist and surrounding area');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('1', 'Rajkot and surrounding area');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('1', 'Jamnagar');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('1', 'Junagadh and surrounding area');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('1', 'Amreli and surrounding area');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('1', 'Balasinor and Panchamahal');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('1', 'Balasinor and Kheda');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('1', 'Umergoan, Wangoan and Boisar');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('1', 'Jetpur, DIU, Dhroll, Mithapur');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('1', 'Dhoraji');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Hassan');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Bellary');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Udupi');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Dharwad/Hubli');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Ramnagara');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Shimoga');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Raichur');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Gadag');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Mandya');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Davanagere');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Koppal');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Chikmagaluru');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Bijapur');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Haveri');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Mysore Rural');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Yadgir');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Gulbarga');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Bangalore Rural');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Bangalore Urban');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Dakshin Kannada');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('2', 'Kodagu');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('3', 'Nashik (Excluding\n Nashik city)');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('3', 'Pune (Excluding\n pune city)');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('3', 'Ambernath & surrounding towns');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('3', 'Bhiwandi & surrounding towns');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('3', 'Raigad (Kharghar to Panvel incl. khopoli & URAN)');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('3', 'Ulhasnagar');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('3', 'Ahmednagar');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('3', 'Dombivali (Gramin)');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('3', 'Solapur(Excluding\n Sholapur city)');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Beawar');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Bikaner');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Nokha');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Ratangarh');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Sardarshar');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Sujangarh');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Taranagar');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Ganganagar');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Hanumangarh');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Nagaur');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Ladnun');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Makrana');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Merta City');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Kuchaman');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Udaipur');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Bhiwadi');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Behror');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Kota');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Tonk');
INSERT INTO `lcodatabase`.`city` (`state_id`, `city_name`) VALUES ('4', 'Rajasthan - Expansion');


INSERT INTO `lcodatabase`.`employee` (`employee_id`, `name`, `email`) VALUES ('100011', 'Adhir', 'adhir@suventure.com');
INSERT INTO `lcodatabase`.`employee` (`employee_id`, `name`) VALUES ('100012', 'Dipankar', 'dipankar@suventure.in');

